name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next
          
      - name: Copy CNAME file
        run: |
          mkdir -p out
          cp CNAME out/

      - name: Build with Next.js
        run: |
          npm run build
          touch out/.nojekyll
          echo "NEXT_PUBLIC_USE_STATIC_DATA=true" >> $GITHUB_ENV
          echo "NODE_ENV=production" >> $GITHUB_ENV
        env:
          # Static data flags
          NEXT_PUBLIC_USE_STATIC_DATA: "true"
          NEXT_PUBLIC_SKIP_PRISMA: "true"
          NODE_ENV: "production"
          
          # Required environment variables (dummy values for static build)
          DATABASE_URL: "file:./dev.db"
          ADMIN_PASSWORD: "dummy-password-for-static-build"
          JWT_SECRET: "dummy-jwt-secret-for-static-build"
          NEXTAUTH_SECRET: "dummy-nextauth-secret-for-static-build"
          NEXTAUTH_URL: "https://recoveredtreasurestx.shop"
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
